version: "3.8"
services:
  db:
    image: "postgres:14.7"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin_role
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=assignment_db